# Generated by Django 2.0.13 on 2020-09-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSpeechDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggeduser', models.CharField(max_length=100)),
                ('loginid', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('textdata', models.CharField(max_length=800)),
                ('link', models.CharField(max_length=500)),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'SpeechTable',
            },
        ),
    ]
