# Generated by Django 2.0.13 on 2020-09-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersspeechdatamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersspeechdatamodel',
            name='link',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
